### ISSUE TITLE
Request for corpus_clean.rb instructions

### ISSUE THREAD

**Issue by GenTxt** [maetl/thematic-automata#1]
Hi:

Thanks for the cool repo. I'm new to ruby and have it running on linux and win7  64bit under ruby-dev 2.3.3. It generates pdf output without a problem. and I like how easy it is to edit the themes.

I would like to create similar data files but I'm unclear how or where to run corpus_clean.rb. 

For example.  I've placed a new "sentences.txt"  corpus in a fresh "data" folder.  I receive the following error in win 7 and a similar one for linux:

$ ruby clean_corpus.rb
c:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in
 `require': cannot load such file -- tools/ner_client (LoadError)
        from c:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_req
uire.rb:55:in `require'
        from clean_corpus.rb:2:in `<main>'

I've edited the script and tried: require_relative  "ner_client"   The script executes quickly but new files are not generated in the "data" folder. 

load "ner_client" produces the same error above.

Any suggestions would be helpful.

Thanks

**Comment by maetl** [comment]
Hi @GenTxt, thanks for your interest. I never really intended this to be runnable outside the context I was working in, and a lot of that code was set up to run as one-off scripts in a terminal window, rather than repeatable. Nevertheless, I’ll try to explain how it fits together so you can look at adapting it.

Firstly, to resolve the load path issues, the best place to look is the Rakefile—line 1 changes the load path to support the `lib` directory in this repo being available.

See: https://github.com/maetl/thematic-automata/blob/master/Rakefile#L1

The approach I’d take to reconstruct the scripts here is to add rake tasks for each specific cleanup task and adapt as necessary.

In the existing `Rakefile` add something like the following:

```ruby
require "tools/clean_corpus"

task :strip_sentences do
  Tools::CleanCorpus.strip_sentences
end

task : strip_punctuation do
  Tools::CleanCorpus.strip_punctuation
end
```

And so forth...

With the `recognize_entities` task, the Stanford NER server needs to be running locally on port `9090` for this to work. 

A rake task I pulled out of a related project which starts up the server is below (not sure if this will work as-is, and note that the env var `STANFORD_NER_PATH` needs to point to the directory path of the downloaded Java service in order to work).

```ruby
namespace :services do
  task :ner do
    classifier = 'english.conll.4class.distsim.crf.ser.gz'
    #classifier = 'english.muc.7class.distsim.crf.ser.gz'
    sh "java -mx1000m -cp '#{ENV['STANFORD_NER_PATH']}/stanford-ner.jar:#{ENV['STANFORD_NER_PATH']}/lib/*' edu.stanford.nlp.ie.NERServer  -loadClassifier #{ENV['STANFORD_NER_PATH']}/classifiers/#{classifier} -port 9090 -outputFormat inlineXML"
  end
end
```

Hope this helps.
